### ISSUE TITLE
Serve Task Failing

### ISSUE THREAD

**Issue by Nawfay** [LePichu/solidjs-deno-example#1]
The serve task keeps on failing after the Build task. The error given is:

`error: Uncaught SyntaxError: The requested module './build.ts' does not provide an export named 'build'
import { build } from "./build.ts"
         ^
    at <anonymous> (file:///home/dishit/solidjs-deno-example/scripts/serve.ts:1:10)`

My deno version is: 
deno 1.28.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.1
typescript 4.8.3

**Comment by LePichu** [comment]
dude how did i not notice this 😔 but yeah i pushed new code today @Dishit79 try now

**Comment by LePichu** [comment]
closing this as it has been stale for a good while now, and it properly works on my end.
